#!/bin/bash
exec > /tmp/debug-my-script.txt 2>&1


#project path configuration
PROJECT_PATH=/var/www/ibiddjango
#export PYTHONPATH=/var/www/
#export DJANGO_SETTINGS_MODULE=ibiddjango.settings

function usage {
	echo 'usage: ibiddjango [start|stop|restart]'
}

function start {
	#start gunicorn
	gunicorn_django $PROJECT_PATH/settings.py -c $PROJECT_PATH/gunicorn.conf.py &
	pid=$!
	echo $pid > $PROJECT_PATH/gunicorn.pid
	
	#Scheduler script
	#python $PROJECT_PATH/manage.py runcommands &
	#pid=$!
	#echo $pid > $PROJECT_PATH/commands.pid
	
}

function stop {
	pid=$(cat < $PROJECT_PATH/gunicorn.pid)
	kill -TERM $pid
	
	#pid=$(cat < $PROJECT_PATH/commands.pid)
	#kill -TERM $pid
	
}

function restart {
	pid=$(cat < $PROJECT_PATH/gunicorn.pid)
	kill -HUP $pid
	
	#pid=$(cat < $PROJECT_PATH/commands.pid)
	#kill -TERM $pid
	#python $PROJECT_PATH/manage.py runcommands &
	#pid=$!
	#echo $pid > $PROJECT_PATH/commands.pid
	
}



if [ $# -lt 1 ]
then
	usage
	exit 1;
fi

case $1 in
	'start') start;;
	'stop') stop;;
	'restart') restart;;
	*) usage;;
esac

exit 0